services:
  backend:
    build:
      context: .
      dockerfile: ./src/Dockerfile
      target: development
    container_name: backend
    hostname: backend
    env_file:
      - ./src/.env
    ports:
      - "8000:8000"
    volumes:
      - ./src/:/opt/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-bullseye
    container_name: db
    environment:
      - POSTGRES_DB=${APP_DATABASE__NAME}
      - POSTGRES_USER=${APP_DATABASE__USER}
      - POSTGRES_PASSWORD=${APP_DATABASE__PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${APP_DATABASE__USER} -d ${APP_DATABASE__NAME}']
      interval: 3s
      timeout: 3s
      retries: 3
      start_period: 5s

volumes:
  postgres_data: