"""empty message

Revision ID: 0a9f854835a7
Revises: 68cfbf828e43
Create Date: 2025-05-29 19:53:27.188308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a9f854835a7'
down_revision: Union[str, None] = '68cfbf828e43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_club_schedule', 'club_schedules', ['billiard_club_id', 'day_of_week'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_club_schedule', 'club_schedules', type_='unique')
    # ### end Alembic commands ###
