"""empty message

Revision ID: 0f40ba7c02dd
Revises: 
Create Date: 2025-05-13 19:16:57.547663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f40ba7c02dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billiard_clubs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('billiard_tables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('billiard_club_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['billiard_club_id'], ['billiard_clubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billiard_tables')
    op.drop_table('billiard_clubs')
    # ### end Alembic commands ###
