"""empty message

Revision ID: 197c0857bece
Revises: 5dd757ac813f
Create Date: 2025-06-02 20:30:32.880931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '197c0857bece'
down_revision: Union[str, None] = '5dd757ac813f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billiard_tables', sa.Column('in_service', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Находится ли стол в техническом обслуживании'))
    op.alter_column('billiard_tables', 'table_type',
               existing_type=postgresql.ENUM('SNOOKER', 'POOL', 'RUSSIAN', name='tabletype'),
               comment='Тип стола',
               existing_nullable=False)
    op.alter_column('billiard_tables', 'price_per_hour',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment='Цена в час',
               existing_nullable=True)
    op.alter_column('club_schedules', 'is_overnight',
               existing_type=sa.BOOLEAN(),
               comment='Затрагивает ли время работы 2 дня',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('club_schedules', 'is_overnight',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Затрагивает ли время работы 2 дня',
               existing_nullable=False)
    op.alter_column('billiard_tables', 'price_per_hour',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               comment=None,
               existing_comment='Цена в час',
               existing_nullable=True)
    op.alter_column('billiard_tables', 'table_type',
               existing_type=postgresql.ENUM('SNOOKER', 'POOL', 'RUSSIAN', name='tabletype'),
               comment=None,
               existing_comment='Тип стола',
               existing_nullable=False)
    op.drop_column('billiard_tables', 'in_service')
    # ### end Alembic commands ###
