"""empty message

Revision ID: 35bef3f301e6
Revises: 0a9f854835a7
Create Date: 2025-06-01 17:57:12.183040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35bef3f301e6'
down_revision: Union[str, None] = '0a9f854835a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billiard_tables', sa.Column('price_per_hour', sa.Numeric(precision=5, scale=2, decimal_return_scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billiard_tables', 'price_per_hour')
    # ### end Alembic commands ###
