"""empty message

Revision ID: 5dd757ac813f
Revises: f00b9e1bf0a6
Create Date: 2025-06-02 10:39:30.290434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision: str = '5dd757ac813f'
down_revision: Union[str, None] = 'f00b9e1bf0a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_tables', sa.Column('phone', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_tables', 'phone')
    # ### end Alembic commands ###
