"""empty message

Revision ID: 68cfbf828e43
Revises: d7f5c4857284
Create Date: 2025-05-18 18:40:22.247579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68cfbf828e43'
down_revision: Union[str, None] = 'd7f5c4857284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('street', sa.String(length=200), nullable=False),
    sa.Column('building', sa.String(length=20), nullable=False),
    sa.Column('apartment', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('billiard_clubs', sa.Column('address_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint(None, 'billiard_clubs', ['address_id'])
    op.create_foreign_key(None, 'billiard_clubs', 'addresses', ['address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'billiard_clubs', type_='foreignkey')
    op.drop_constraint(None, 'billiard_clubs', type_='unique')
    op.drop_column('billiard_clubs', 'address_id')
    op.drop_table('addresses')
    # ### end Alembic commands ###
