"""empty message

Revision ID: e225913c6cbd
Revises: 0f40ba7c02dd
Create Date: 2025-05-18 17:38:36.457803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision: str = 'e225913c6cbd'
down_revision: Union[str, None] = '0f40ba7c02dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('SNOOKER', 'POOL', 'RUSSIAN', name='tabletype').create(op.get_bind())
    op.add_column('billiard_clubs', sa.Column('phone', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=True))
    op.add_column('billiard_clubs', sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=True))
    op.add_column('billiard_clubs', sa.Column('photo', sa.String(), nullable=True))
    op.add_column('billiard_tables', sa.Column('table_type', postgresql.ENUM('SNOOKER', 'POOL', 'RUSSIAN', name='tabletype', create_type=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billiard_tables', 'table_type')
    op.drop_column('billiard_clubs', 'photo')
    op.drop_column('billiard_clubs', 'email')
    op.drop_column('billiard_clubs', 'phone')
    sa.Enum('SNOOKER', 'POOL', 'RUSSIAN', name='tabletype').drop(op.get_bind())
    # ### end Alembic commands ###
