"""empty message

Revision ID: ef8714c237d1
Revises: d77a3910f2ac
Create Date: 2025-06-18 14:59:13.176248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef8714c237d1'
down_revision: Union[str, None] = 'd77a3910f2ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('billiard_club_id', sa.Uuid(), nullable=False),
    sa.Column('table_type', postgresql.ENUM('SNOOKER', 'POOL', 'RUSSIAN', name='tabletype', create_type=False), nullable=True, comment='Тип стола по которому действует цена, если null действует для всех столов'),
    sa.Column('days_of_week', postgresql.ARRAY(sa.Integer()), nullable=False, comment='Дни недели когда действует цена, если пустой массив - день недели не влияет на цену'),
    sa.Column('start_time', sa.Time(timezone=True), nullable=True),
    sa.Column('end_time', sa.Time(timezone=True), nullable=True),
    sa.Column('price_per_hour', sa.Numeric(precision=5, scale=2, decimal_return_scale=2), nullable=True, comment='Цена в час'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['billiard_club_id'], ['billiard_clubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_rules')
    # ### end Alembic commands ###
